export const noticeTableData = [
  {
    id: 1,
    isNotice: true,
    title: "사이트 유지 보수 안내",
    author: "관리자",
    date: "2024.05.01",
    views: "1,100",
  },
  {
    id: 2,
    isNotice: true,
    title: "개인정보 처리방침 변경 안내",
    author: "관리자",
    date: "2024.05.05",
    views: "980",
  },
  {
    id: 3,
    isNotice: true,
    title: "서비스 약관 변경 안내",
    author: "관리자",
    date: "2024.05.10",
    views: "850",
  },
  {
    id: 4,
    isNotice: true,
    title: "정기 점검 공지",
    author: "관리자",
    date: "2024.05.15",
    views: "900",
  },
  {
    id: 5,
    isNotice: true,
    title: "시스템 업그레이드 예정 안내",
    author: "관리자",
    date: "2024.05.20",
    views: "750",
  },
  {
    id: 6,
    isNotice: true,
    title: "긴급 서버 점검 안내",
    author: "관리자",
    date: "2024.05.25",
    views: "670",
  },
  {
    id: 7,
    isNotice: true,
    title: "이용 약관 개정 안내",
    author: "관리자",
    date: "2024.05.30",
    views: "600",
  },
  {
    id: 8,
    isNotice: true,
    title: "신규 서비스 출시 안내",
    author: "관리자",
    date: "2024.06.01",
    views: "500",
  },
  {
    id: 9,
    isNotice: true,
    title: "고객센터 운영 시간 변경 안내",
    author: "관리자",
    date: "2024.06.05",
    views: "450",
  },
  {
    id: 10,
    isNotice: true,
    title: "보안 강화 업데이트 공지",
    author: "관리자",
    date: "2024.06.10",
    views: "400",
  },
];

export const communityTableData = [
  {
    id: 11,
    isNotice: true,
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,234",
  },
  {
    id: 12,
    isNotice: true,
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,234",
  },
  {
    id: 13,
    isNotice: true,
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,234",
  },
  {
    id: 14,
    isNotice: false,
    category: "커뮤니티",
    title: "비트코인 1억 갔네",
    author: "김코인",
    date: "2024.03.21 03:38:00",
    views: "1,243",
    likes: 99,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [
      {
        id: 1,
        author: "박코인",
        date: "2024.03.02 09:15:30",
        content: "안내려갈걸요?",
        replies: [
          {
            id: 2,
            author: "김코인",
            date: "2024.03.03 10:45:00",
            content: "내려감",
          },
        ],
      },
      {
        id: 3,
        author: "김코인",
        date: "2024.03.04 14:20:10",
        content: "ㅋㅋㅋ",
        replies: [],
      },
    ],
  },
  {
    id: 15,
    isNotice: false,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.03.21 03:38:00",
    views: "1,242",
    likes: 98,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 16,
    isNotice: false,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.03.21 03:38:00",
    views: "1,241",
    likes: 97,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 17,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,240",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 18,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,239",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 19,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,238",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 20,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,237",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 21,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,236",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 22,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,235",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
  {
    id: 23,
    isNotice: true,
    category: "커뮤니티",
    title: "오픈채팅 및 카카오톡 아이디 공유 영구제재 안내",
    author: "관리자",
    date: "2024.08.01",
    views: "1,234",
    likes: 0,
    content: "<p>비트코인 1억 갔네</p><br><p>근데 다시 내려갈 듯</p>",
    comments: [],
  },
];
